import { Service } from "@/types/service";

export const SERVICES: Service[] = [
  // Audits & Compliance - ACCOUNTING SERVICES
  {
    id: "audit-1",
    sectionId: "audits",
    subcategory: "Accounting Services",
    title: "Annual Accounts Preparation",
    description:
      "Comprehensive annual accounts preparation for compliance and business insight.",
    price: 299,
    features: [
      "Full statutory accounts",
      "HMRC and Companies House filing",
      "Year-end tax review",
    ],
    formFields: [
      {
        name: "accountingPeriod",
        label: "Accounting Period",
        variant: "text",
        required: true,
      },
      {
        name: "companyType",
        label: "Company Type",
        variant: "dropdown",
        options: ["Limited Company", "LLP", "PLC", "Other"],
        required: true,
      },
      {
        name: "turnover",
        label: "Annual Turnover",
        variant: "number",
        required: true,
      },
      {
        name: "employees",
        label: "Number of Employees",
        variant: "number",
        required: true,
      },
      {
        name: "specialRequirements",
        label: "Special Requirements",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-2",
    sectionId: "audits",
    subcategory: "Accounting Services",
    title: "Audit and Assurance",
    description:
      "Independent audit and assurance services to build trust and transparency.",
    price: 499,
    features: [
      "Detailed audit report",
      "Risk assessment",
      "Regulatory compliance",
    ],
    formFields: [
      {
        name: "auditType",
        label: "Type of Audit",
        variant: "dropdown",
        options: ["Statutory", "Internal", "External", "Other"],
        required: true,
      },
      {
        name: "regulatoryBody",
        label: "Regulatory Body",
        variant: "text",
        required: true,
      },
      {
        name: "auditScope",
        label: "Audit Scope",
        variant: "dropdown",
        options: ["Full Audit", "Limited Review", "Agreed Procedures"],
        required: true,
      },
      {
        name: "deadline",
        label: "Required Deadline",
        variant: "text",
        required: true,
      },
      {
        name: "additionalNotes",
        label: "Additional Notes",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-3",
    sectionId: "audits",
    subcategory: "Accounting Services",
    title: "Company Formations and Secretarial",
    description:
      "Company formation and secretarial services for new and existing businesses.",
    price: 180,
    features: [
      "Company registration",
      "Secretarial compliance",
      "Annual returns",
    ],
    formFields: [
      {
        name: "formationType",
        label: "Type of Formation",
        variant: "dropdown",
        options: ["Limited Company", "LLP", "PLC", "Other"],
        required: true,
      },
      {
        name: "existingCompany",
        label: "Is this for an existing company?",
        variant: "dropdown",
        options: ["Yes", "No"],
        required: true,
      },
      {
        name: "businessActivity",
        label: "Main Business Activity",
        variant: "text",
        required: true,
      },
      {
        name: "shareholders",
        label: "Number of Shareholders",
        variant: "number",
        required: true,
      },
      {
        name: "urgentProcessing",
        label: "Urgent Processing Required?",
        variant: "dropdown",
        options: ["Yes", "No"],
        required: false,
      },
    ],
  },
  {
    id: "audit-4",
    sectionId: "audits",
    subcategory: "Accounting Services",
    title: "Management Accounts and Information",
    description:
      "Preparation and analysis of management accounts and business information.",
    price: 220,
    features: [
      "Monthly/quarterly management accounts",
      "Performance analysis",
      "Custom business reports",
    ],
    formFields: [
      {
        name: "reportFrequency",
        label: "Report Frequency",
        variant: "dropdown",
        options: ["Monthly", "Quarterly", "Annually"],
        required: true,
      },
      {
        name: "customReports",
        label: "Need Custom Reports?",
        variant: "dropdown",
        options: ["Yes", "No"],
        required: true,
      },
      {
        name: "reportTypes",
        label: "Types of Reports Needed",
        variant: "dropdown",
        options: ["P&L", "Balance Sheet", "Cash Flow", "KPI Reports", "All"],
        required: true,
      },
      {
        name: "startDate",
        label: "Start Date for Reports",
        variant: "text",
        required: true,
      },
      {
        name: "specificRequirements",
        label: "Specific Requirements",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-5",
    sectionId: "audits",
    subcategory: "Accounting Services",
    title: "Bookkeeping/Payroll",
    description:
      "Bookkeeping and payroll services for businesses of all sizes.",
    price: 120,
    features: [
      "Accurate bookkeeping",
      "Payroll processing",
      "HMRC submissions",
    ],
    formFields: [
      {
        name: "numEmployees",
        label: "Number of Employees",
        variant: "number",
        required: true,
      },
      {
        name: "payrollFrequency",
        label: "Payroll Frequency",
        variant: "dropdown",
        options: ["Weekly", "Monthly", "Quarterly"],
        required: true,
      },
      {
        name: "bookkeepingNeeded",
        label: "Bookkeeping Services Needed?",
        variant: "dropdown",
        options: ["Yes", "No"],
        required: true,
      },
      {
        name: "softwareUsed",
        label: "Current Software Used",
        variant: "text",
        required: true,
      },
      {
        name: "additionalServices",
        label: "Additional Services Required",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // Audits & Compliance - ADDED VALUE SERVICES
  {
    id: "audit-6",
    sectionId: "audits",
    subcategory: "Accounting Services",
    title: "Information Technology and Accounting Software",
    description:
      "Advice and support for IT systems and accounting software integration.",
    price: 150,
    features: ["Software selection", "System setup", "Ongoing support"],
    formFields: [
      {
        name: "softwareType",
        label: "Type of Software",
        variant: "text",
        required: true,
      },
      {
        name: "integrationNeeded",
        label: "Integration Needed?",
        variant: "dropdown",
        options: ["Yes", "No"],
        required: true,
      },
      {
        name: "currentSystems",
        label: "Current Systems in Use",
        variant: "text",
        required: true,
      },
      {
        name: "userCount",
        label: "Number of Users",
        variant: "number",
        required: true,
      },
      {
        name: "specificNeeds",
        label: "Specific IT Needs",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-7",
    sectionId: "audits",
    subcategory: "Added Value Services",
    title: "Management Systems",
    description:
      "Implementation and review of management systems for business efficiency.",
    price: 200,
    features: [
      "System design",
      "Process improvement",
      "Performance monitoring",
    ],
    formFields: [
      {
        name: "systemType",
        label: "Type of Management System",
        variant: "dropdown",
        options: ["ISO 9001", "ISO 14001", "ISO 27001", "Custom", "Other"],
        required: true,
      },
      {
        name: "implementationPhase",
        label: "Implementation Phase",
        variant: "dropdown",
        options: ["Planning", "Implementation", "Review", "Maintenance"],
        required: true,
      },
      {
        name: "companySize",
        label: "Company Size",
        variant: "dropdown",
        options: ["Small (1-10)", "Medium (11-50)", "Large (50+)"],
        required: true,
      },
      {
        name: "certificationNeeded",
        label: "Certification Required?",
        variant: "dropdown",
        options: ["Yes", "No"],
        required: true,
      },
      {
        name: "currentProcesses",
        label: "Current Processes Description",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-8",
    sectionId: "audits",
    subcategory: "Added Value Services",
    title: "Raising Finance and Business Plans",
    description:
      "Support with raising finance and preparing business plans for growth.",
    price: 250,
    features: [
      "Business plan creation",
      "Finance sourcing advice",
      "Investor presentations",
    ],
    formFields: [
      {
        name: "financeAmount",
        label: "Amount to Raise",
        variant: "number",
        required: true,
      },
      {
        name: "financeType",
        label: "Type of Finance",
        variant: "dropdown",
        options: ["Loan", "Investment", "Grant", "Crowdfunding", "Other"],
        required: true,
      },
      {
        name: "purpose",
        label: "Purpose of Finance",
        variant: "dropdown",
        options: [
          "Expansion",
          "Working Capital",
          "Equipment",
          "Marketing",
          "Other",
        ],
        required: true,
      },
      {
        name: "timeline",
        label: "Required Timeline",
        variant: "dropdown",
        options: ["Immediate", "1-3 months", "3-6 months", "6+ months"],
        required: true,
      },
      {
        name: "businessDetails",
        label: "Business Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-9",
    sectionId: "audits",
    subcategory: "Added Value Services",
    title: "Business Growth",
    description: "Strategies and support for sustainable business growth.",
    price: 220,
    features: ["Growth strategy", "Market analysis", "Performance tracking"],
    formFields: [
      {
        name: "growthTarget",
        label: "Growth Target",
        variant: "dropdown",
        options: [
          "Revenue Growth",
          "Market Expansion",
          "Product Development",
          "Operational Efficiency",
        ],
        required: true,
      },
      {
        name: "timeframe",
        label: "Growth Timeframe",
        variant: "dropdown",
        options: ["6 months", "1 year", "2 years", "3+ years"],
        required: true,
      },
      {
        name: "currentChallenges",
        label: "Current Challenges",
        variant: "dropdown",
        options: [
          "Market Competition",
          "Funding",
          "Operations",
          "Technology",
          "Other",
        ],
        required: true,
      },
      {
        name: "industry",
        label: "Industry/Sector",
        variant: "text",
        required: true,
      },
      {
        name: "growthDetails",
        label: "Growth Strategy Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-10",
    sectionId: "audits",
    subcategory: "Added Value Services",
    title: "Strategic Planning",
    description:
      "Strategic planning services to help your business achieve its goals.",
    price: 210,
    features: ["Goal setting", "Action plans", "Progress reviews"],
    formFields: [
      {
        name: "planningScope",
        label: "Planning Scope",
        variant: "dropdown",
        options: [
          "Short-term (1 year)",
          "Medium-term (3 years)",
          "Long-term (5+ years)",
        ],
        required: true,
      },
      {
        name: "focusAreas",
        label: "Focus Areas",
        variant: "dropdown",
        options: ["Financial", "Operational", "Marketing", "Technology", "All"],
        required: true,
      },
      {
        name: "companyStage",
        label: "Company Stage",
        variant: "dropdown",
        options: ["Startup", "Growth", "Mature", "Transition"],
        required: true,
      },
      {
        name: "keyObjectives",
        label: "Key Objectives",
        variant: "text",
        required: true,
      },
      {
        name: "strategicDetails",
        label: "Strategic Planning Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-11",
    sectionId: "audits",
    subcategory: "Added Value Services",
    title: "Business Valuations",
    description:
      "Professional business valuation services for various purposes.",
    price: 300,
    features: ["Valuation reports", "Due diligence", "Market comparisons"],
    formFields: [
      {
        name: "valuationPurpose",
        label: "Purpose of Valuation",
        variant: "dropdown",
        options: ["Sale", "Purchase", "Investment", "Legal", "Tax", "Other"],
        required: true,
      },
      {
        name: "valuationMethod",
        label: "Preferred Valuation Method",
        variant: "dropdown",
        options: ["Asset-based", "Income-based", "Market-based", "Hybrid"],
        required: true,
      },
      {
        name: "businessType",
        label: "Business Type",
        variant: "dropdown",
        options: ["Service", "Manufacturing", "Retail", "Technology", "Other"],
        required: true,
      },
      {
        name: "annualRevenue",
        label: "Annual Revenue",
        variant: "number",
        required: true,
      },
      {
        name: "valuationDetails",
        label: "Valuation Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "audit-12",
    sectionId: "audits",
    subcategory: "Added Value Services",
    title: "Translation & Interpretation",
    description:
      "Translation and interpretation services for business and financial documents.",
    price: 100,
    features: [
      "Document translation",
      "Interpretation services",
      "Certified translations",
    ],
    formFields: [
      {
        name: "language",
        label: "Language Needed",
        variant: "text",
        required: true,
      },
      {
        name: "serviceType",
        label: "Service Type",
        variant: "dropdown",
        options: [
          "Document Translation",
          "Interpretation",
          "Certified Translation",
        ],
        required: true,
      },
      {
        name: "documentType",
        label: "Document Type",
        variant: "dropdown",
        options: ["Financial", "Legal", "Technical", "Marketing", "Other"],
        required: true,
      },
      {
        name: "urgency",
        label: "Urgency Level",
        variant: "dropdown",
        options: ["Standard", "Express", "Rush"],
        required: true,
      },
      {
        name: "translationDetails",
        label: "Translation Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // Payroll Services
  {
    id: "payroll-1",
    sectionId: "payroll",
    subcategory: "PAYE and NI",
    title: "Payroll and compliance",
    description:
      "Payroll processing and compliance with PAYE and NI regulations.",
    price: 120,
    features: ["Payroll and compliance"],
    formFields: [
      {
        name: "payrollPeriod",
        label: "Payroll Period",
        variant: "dropdown",
        options: ["Weekly", "Monthly", "Quarterly"],
        required: true,
      },
      {
        name: "employeeCount",
        label: "Number of Employees",
        variant: "number",
        required: true,
      },
      {
        name: "payrollSoftware",
        label: "Current Payroll Software",
        variant: "text",
        required: true,
      },
      {
        name: "complianceNeeds",
        label: "Compliance Requirements",
        variant: "dropdown",
        options: [
          "Basic PAYE",
          "Full Compliance",
          "Pension Auto-enrolment",
          "All",
        ],
        required: true,
      },
      {
        name: "payrollDetails",
        label: "Payroll Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "payroll-2",
    sectionId: "payroll",
    subcategory: "PAYE and NI",
    title: "End of year returns and P11D's",
    description:
      "Preparation and filing of end of year payroll returns and P11D forms.",
    price: 80,
    features: ["End of year returns and P11D's"],
    formFields: [
      {
        name: "taxYear",
        label: "Tax Year",
        variant: "text",
        required: true,
      },
      {
        name: "returnType",
        label: "Return Type",
        variant: "dropdown",
        options: ["P11D", "P60", "P45", "All"],
        required: true,
      },
      {
        name: "employeeCount",
        label: "Number of Employees",
        variant: "number",
        required: true,
      },
      {
        name: "benefitsProvided",
        label: "Benefits Provided",
        variant: "dropdown",
        options: ["Company Car", "Health Insurance", "Other Benefits", "None"],
        required: true,
      },
      {
        name: "returnDetails",
        label: "Return Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "payroll-3",
    sectionId: "payroll",
    subcategory: "PAYE and NI",
    title: "Employment status disputes and IR35",
    description:
      "Advice and support for employment status disputes and IR35 compliance.",
    price: 150,
    features: ["Employment status disputes and IR35"],
    formFields: [
      {
        name: "disputeType",
        label: "Type of Dispute",
        variant: "dropdown",
        options: [
          "IR35",
          "Employment Status",
          "Contractor Classification",
          "Other",
        ],
        required: true,
      },
      {
        name: "contractorType",
        label: "Contractor Type",
        variant: "dropdown",
        options: ["Individual", "Limited Company", "Partnership", "Other"],
        required: true,
      },
      {
        name: "contractDuration",
        label: "Contract Duration",
        variant: "dropdown",
        options: ["Short-term", "Long-term", "Ongoing", "Completed"],
        required: true,
      },
      {
        name: "industry",
        label: "Industry",
        variant: "text",
        required: true,
      },
      {
        name: "disputeDetails",
        label: "Dispute Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // Taxation Services
  // TAXATION, Sole Traders and Partnerships
  {
    id: "tax-1",
    sectionId: "taxation",
    subcategory: "TAXATION, Sole Traders and Partnerships",
    title: "Self Assessment",
    description:
      "Self assessment for sole traders and partnerships, including HMRC enquiries and investigations.",
    price: 120,
    features: ["Self assessment", "HMRC enquiries and investigations"],
    formFields: [
      {
        name: "selfAssessmentType",
        label: "Type of Self Assessment",
        variant: "dropdown",
        options: ["Individual", "Partnership"],
        required: true,
      },
      {
        name: "incomeSources",
        label: "Income Sources",
        variant: "dropdown",
        options: [
          "Employment",
          "Self-employment",
          "Property",
          "Investments",
          "Multiple",
        ],
        required: true,
      },
      {
        name: "annualIncome",
        label: "Annual Income",
        variant: "number",
        required: true,
      },
      {
        name: "previousReturns",
        label: "Previous Returns Filed?",
        variant: "dropdown",
        options: ["Yes", "No", "First Time"],
        required: true,
      },
      {
        name: "assessmentDetails",
        label: "Assessment Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "tax-2",
    sectionId: "taxation",
    subcategory: "TAXATION, Sole Traders and Partnerships",
    title: "Tax Planning & Trusts",
    description:
      "Tax planning, trusts, estates, inheritance tax, and Construction Industry Scheme support.",
    price: 140,
    features: [
      "Tax planning",
      "Trusts, estates and inheritance tax",
      "Construction Industry Scheme",
    ],
    formFields: [
      {
        name: "planningArea",
        label: "Area of Planning",
        variant: "dropdown",
        options: [
          "Income Tax",
          "Capital Gains",
          "Inheritance Tax",
          "Trust Planning",
          "CIS",
        ],
        required: true,
      },
      {
        name: "assetValue",
        label: "Asset Value",
        variant: "number",
        required: true,
      },
      {
        name: "planningObjective",
        label: "Planning Objective",
        variant: "dropdown",
        options: [
          "Tax Reduction",
          "Asset Protection",
          "Succession Planning",
          "Compliance",
        ],
        required: true,
      },
      {
        name: "timeframe",
        label: "Planning Timeframe",
        variant: "dropdown",
        options: ["Immediate", "Short-term", "Long-term"],
        required: true,
      },
      {
        name: "planningDetails",
        label: "Planning Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "tax-3",
    sectionId: "taxation",
    subcategory: "TAXATION, Sole Traders and Partnerships",
    title: "Tax Disputes & Investigations",
    description:
      "Support for contentious tax dispute work and tax investigations.",
    price: 160,
    features: ["Contentious tax dispute work", "Tax investigation"],
    formFields: [
      {
        name: "disputeType",
        label: "Type of Dispute",
        variant: "dropdown",
        options: [
          "HMRC Investigation",
          "Tax Dispute",
          "Penalty Appeal",
          "Other",
        ],
        required: true,
      },
      {
        name: "taxYear",
        label: "Tax Year in Question",
        variant: "text",
        required: true,
      },
      {
        name: "amountInvolved",
        label: "Amount Involved",
        variant: "number",
        required: true,
      },
      {
        name: "currentStage",
        label: "Current Stage",
        variant: "dropdown",
        options: ["Initial Notice", "Under Review", "Appeal", "Tribunal"],
        required: true,
      },
      {
        name: "disputeDetails",
        label: "Dispute Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // CORPORATION TAX
  {
    id: "tax-4",
    sectionId: "taxation",
    subcategory: "CORPORATION TAX",
    title: "CTSA - Self Assessment",
    description:
      "Corporation Tax Self Assessment and HMRC enquiries/investigations.",
    price: 180,
    features: ["CTSA - Self assessment", "HMRC enquiries and investigations"],
    formFields: [
      {
        name: "ctsaType",
        label: "CTSA Type",
        variant: "dropdown",
        options: ["Full CTSA", "Abbreviated", "Dormant Company"],
        required: true,
      },
      {
        name: "accountingPeriod",
        label: "Accounting Period",
        variant: "text",
        required: true,
      },
      {
        name: "turnover",
        label: "Annual Turnover",
        variant: "number",
        required: true,
      },
      {
        name: "profitLevel",
        label: "Profit Level",
        variant: "dropdown",
        options: ["Loss", "Small Profit", "Large Profit"],
        required: true,
      },
      {
        name: "ctsaDetails",
        label: "CTSA Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "tax-5",
    sectionId: "taxation",
    subcategory: "CORPORATION TAX",
    title: "Corporation Tax Planning",
    description: "Corporation tax planning for businesses.",
    price: 150,
    features: ["Tax planning"],
    formFields: [
      {
        name: "planningObjective",
        label: "Planning Objective",
        variant: "dropdown",
        options: ["Tax Reduction", "Compliance", "Restructuring", "Investment"],
        required: true,
      },
      {
        name: "companySize",
        label: "Company Size",
        variant: "dropdown",
        options: ["Small", "Medium", "Large"],
        required: true,
      },
      {
        name: "annualTurnover",
        label: "Annual Turnover",
        variant: "number",
        required: true,
      },
      {
        name: "planningArea",
        label: "Planning Area",
        variant: "dropdown",
        options: ["Capital Allowances", "R&D Relief", "Group Relief", "Other"],
        required: true,
      },
      {
        name: "planningDetails",
        label: "Planning Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "tax-6",
    sectionId: "taxation",
    subcategory: "CORPORATION TAX",
    title: "Tax Investigation Fees Insurance",
    description: "Insurance for tax investigation fees for corporations.",
    price: 100,
    features: ["Tax investigation fees insurance"],
    formFields: [
      {
        name: "insuranceType",
        label: "Insurance Type",
        variant: "dropdown",
        options: ["Basic", "Comprehensive", "Premium"],
        required: true,
      },
      {
        name: "coverageAmount",
        label: "Coverage Amount",
        variant: "dropdown",
        options: ["£25,000", "£50,000", "£100,000", "£250,000"],
        required: true,
      },
      {
        name: "companyType",
        label: "Company Type",
        variant: "dropdown",
        options: ["Limited Company", "LLP", "Partnership", "Other"],
        required: true,
      },
      {
        name: "riskLevel",
        label: "Risk Level",
        variant: "dropdown",
        options: ["Low", "Medium", "High"],
        required: true,
      },
      {
        name: "insuranceDetails",
        label: "Insurance Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // VAT
  {
    id: "tax-7",
    sectionId: "taxation",
    subcategory: "VAT",
    title: "VAT Registration",
    description: "VAT registration services for businesses.",
    price: 90,
    features: ["Registration"],
    formFields: [
      {
        name: "vatScheme",
        label: "VAT Scheme",
        variant: "dropdown",
        options: ["Standard", "Flat Rate", "Annual", "Other"],
        required: true,
      },
      {
        name: "businessType",
        label: "Business Type",
        variant: "dropdown",
        options: ["Sole Trader", "Partnership", "Limited Company", "Other"],
        required: true,
      },
      {
        name: "annualTurnover",
        label: "Annual Turnover",
        variant: "number",
        required: true,
      },
      {
        name: "registrationUrgency",
        label: "Registration Urgency",
        variant: "dropdown",
        options: ["Standard", "Express", "Immediate"],
        required: true,
      },
      {
        name: "vatDetails",
        label: "VAT Registration Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "tax-8",
    sectionId: "taxation",
    subcategory: "VAT",
    title: "VAT Returns",
    description: "Preparation and filing of VAT returns.",
    price: 110,
    features: ["VAT Returns"],
    formFields: [
      {
        name: "returnPeriod",
        label: "Return Period",
        variant: "dropdown",
        options: ["Monthly", "Quarterly", "Annually"],
        required: true,
      },
      {
        name: "vatScheme",
        label: "VAT Scheme",
        variant: "dropdown",
        options: ["Standard", "Flat Rate", "Annual", "Other"],
        required: true,
      },
      {
        name: "returnCount",
        label: "Number of Returns",
        variant: "number",
        required: true,
      },
      {
        name: "complexity",
        label: "Return Complexity",
        variant: "dropdown",
        options: ["Simple", "Standard", "Complex"],
        required: true,
      },
      {
        name: "returnDetails",
        label: "Return Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "tax-9",
    sectionId: "taxation",
    subcategory: "VAT",
    title: "VAT Planning & Disputes",
    description: "VAT planning and dispute resolution services.",
    price: 130,
    features: ["Planning and disputes"],
    formFields: [
      {
        name: "disputeNature",
        label: "Nature of Dispute",
        variant: "dropdown",
        options: [
          "VAT Assessment",
          "Penalty Appeal",
          "Planning Query",
          "Other",
        ],
        required: true,
      },
      {
        name: "amountInvolved",
        label: "Amount Involved",
        variant: "number",
        required: true,
      },
      {
        name: "disputeStage",
        label: "Dispute Stage",
        variant: "dropdown",
        options: ["Initial", "Review", "Appeal", "Tribunal"],
        required: true,
      },
      {
        name: "vatPeriod",
        label: "VAT Period",
        variant: "text",
        required: true,
      },
      {
        name: "disputeDetails",
        label: "Dispute Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // Business Start-up & Planning
  // BUSINESS START-UPS
  {
    id: "plan-1",
    sectionId: "planning",
    subcategory: "BUSINESS START-UPS",
    title: "General Issues",
    description:
      "Advice on general business start-up issues, company formation, and Construction Industry Scheme.",
    price: 120,
    features: [
      "General Issues",
      "Company formation",
      "Construction Industry Scheme",
    ],
    formFields: [
      {
        name: "issueType",
        label: "Type of Issue",
        variant: "dropdown",
        options: [
          "Company Formation",
          "CIS Registration",
          "Business Structure",
          "Other",
        ],
        required: true,
      },
      {
        name: "businessStage",
        label: "Business Stage",
        variant: "dropdown",
        options: ["Planning", "Startup", "Early Growth", "Established"],
        required: true,
      },
      {
        name: "industry",
        label: "Industry",
        variant: "text",
        required: true,
      },
      {
        name: "fundingStatus",
        label: "Funding Status",
        variant: "dropdown",
        options: ["Self-funded", "Seeking Investment", "Grant-funded", "Other"],
        required: true,
      },
      {
        name: "issueDetails",
        label: "Issue Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "plan-2",
    sectionId: "planning",
    subcategory: "BUSINESS START-UPS",
    title: "Raising Finance and Business Plans",
    description:
      "Support with raising finance and preparing business plans for start-ups.",
    price: 150,
    features: ["Raising finance and business plans"],
    formFields: [
      {
        name: "financeSource",
        label: "Source of Finance",
        variant: "dropdown",
        options: ["Bank Loan", "Investment", "Grant", "Crowdfunding", "Other"],
        required: true,
      },
      {
        name: "amountRequired",
        label: "Amount Required",
        variant: "number",
        required: true,
      },
      {
        name: "businessPlanType",
        label: "Business Plan Type",
        variant: "dropdown",
        options: ["Executive Summary", "Full Plan", "Financial Model", "All"],
        required: true,
      },
      {
        name: "timeline",
        label: "Timeline",
        variant: "dropdown",
        options: ["Immediate", "1-3 months", "3-6 months", "6+ months"],
        required: true,
      },
      {
        name: "financeDetails",
        label: "Finance Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "plan-3",
    sectionId: "planning",
    subcategory: "BUSINESS START-UPS",
    title: "Business Growth, Strategic & Tax Planning",
    description:
      "Business growth, strategic planning, and tax planning for new businesses.",
    price: 140,
    features: ["Business growth", "Strategic planning", "Tax planning"],
    formFields: [
      {
        name: "growthGoal",
        label: "Growth Goal",
        variant: "dropdown",
        options: [
          "Revenue Growth",
          "Market Expansion",
          "Product Development",
          "Operational Efficiency",
        ],
        required: true,
      },
      {
        name: "timeframe",
        label: "Growth Timeframe",
        variant: "dropdown",
        options: ["6 months", "1 year", "2 years", "3+ years"],
        required: true,
      },
      {
        name: "currentRevenue",
        label: "Current Annual Revenue",
        variant: "number",
        required: true,
      },
      {
        name: "planningFocus",
        label: "Planning Focus",
        variant: "dropdown",
        options: ["Strategic", "Tax", "Operational", "All"],
        required: true,
      },
      {
        name: "growthDetails",
        label: "Growth Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
  // General Services
  {
    id: "plan-4",
    sectionId: "planning",
    subcategory: "General Services",
    title: "Offshore Incorporation",
    description: "Expert advice and setup for offshore company incorporation.",
    price: 400,
    features: ["Offshore incorporation"],
    formFields: [
      {
        name: "jurisdiction",
        label: "Jurisdiction",
        variant: "dropdown",
        options: ["Cayman Islands", "BVI", "Jersey", "Guernsey", "Other"],
        required: true,
      },
      {
        name: "incorporationType",
        label: "Incorporation Type",
        variant: "dropdown",
        options: ["Standard", "Exempt", "Segregated Portfolio", "Other"],
        required: true,
      },
      {
        name: "businessPurpose",
        label: "Business Purpose",
        variant: "dropdown",
        options: ["Investment", "Trading", "Holding", "Other"],
        required: true,
      },
      {
        name: "urgency",
        label: "Urgency Level",
        variant: "dropdown",
        options: ["Standard", "Express", "Rush"],
        required: true,
      },
      {
        name: "offshoreDetails",
        label: "Offshore Details",
        variant: "textarea",
        required: false,
      },
    ],
  },
];

export function getServiceById(id: string) {
  return SERVICES.find((service) => service.id === id);
}
